### ISSUE TITLE
Installment siden og download til excel

### ISSUE THREAD

**Issue by LauFinnPedersen** [TelePost/repayment.tusass.gl#27]
Under installments 

Kolonnenavn, (eksempelværdi)
ID (1)
Agreement ID  (1) NY
Name (Hans Hansen) NY
PostPaidNo (10565656) NY
DueDate (29-10-2019)
PaidDate (29-10-2019) eller tom NY
AmountDue (1.284,00)
InstallmentStatus (Aktiv)
NumberOfPayments (2)

Under installments skal vi kunne filtrere på 
- installment status, 
- Fra DueDate 
- Til DueDate
- Fra PaidDate
- Til PaidDate

Der skal være funktion "Download til excel"

![image](https://user-images.githubusercontent.com/38666933/56811198-f75ac100-6816-11e9-9ced-bbcb0a49d594.png)

Dermed kan vi håndtere disse to krav fra debitor

Rapport over alle afdrag for måneden pr. abonnementsnr og postpaid kundenr  – til månedlig afstemning til finans. 

Rapport over månedens misligeholdte rater, pr. abonnementsnr og postpaidkundenr samt tusassreference (mobil, Internetforbindelse)

**Comment by BsiKlintra** [comment]
Rapport delen flyttet til ny issue (#37)
