### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by LauFinnPedersen** [TelePost/repayment.tusass.gl#34]
Tile på Dashboard

Første række:
Total Agreements, Active Agreements, Paused Agreements, Closed Agreements

Anden række:
Total Remaining Sum, Active Remaining Sum, Paused Remaining Sum, Closed Remaining Sum

Tredje række:
Total Paid Sum, Active Paid Sum, Paused Paid Sum, Closed Paid Sum

Fjerde række:
Total Due+5 Sum, Total Due+5 Agreements
 

- Due+5 er kun hvor payment date er overskredet med 5 dage
- Jeg tror "Payment sum" tæller afviste betalinger med. Det er en fejl.

**Comment by BsiKlintra** [comment]
Anden række, "Closed Remaining Sum", vil den ikke altid være 0?

**Comment by LauFinnPedersen** [comment]
Hej Bergar

Jo – det var bare for at være konsistent i kolonnerne.. Måske man kan tydeliggøre det ved at give hver kolonne forskellig nuance i farve og sætte overskrifter

[cid:image002.png@01D500E4.D7964270]



Inussiarnersumik inuulluaqqusillunga / Med venlig hilsen
Lau Finn Pedersen
Fra: BsiKlintra <notifications@github.com>
Sendt: 2. maj 2019 10:22
Til: TelePost/repayment.tusass.gl <repayment.tusass.gl@noreply.github.com>
Cc: Lau Finn Pedersen (LAUP) <laup@telepost.gl>; Author <author@noreply.github.com>
Emne: Re: [TelePost/repayment.tusass.gl] Dashboard (#34)


Anden række, "Closed Remaining Sum", vil den ikke altid være 0?
