### ISSUE TITLE
Navigering tilbage i appilkation

### ISSUE THREAD

**Issue by LauFinnPedersen** [TelePost/repayment.tusass.gl#7]
For at navigere tilbage skal man bruge browserens tilbage funktion

Her er jeg i 
Repayment Agreement > Vis Agreement > Opret agreement file
Kan man enten vise et navigationslink som ovenfor..  "breadcrum" tror jeg det hedder eller noget andet?

Lige i dette tilfælde skal der måske også være en annuller

![image](https://user-images.githubusercontent.com/38666933/55551871-92e68f00-56ba-11e9-998a-c707664ebdca.png)

**Comment by BsiKlintra** [comment]
https://packagist.org/packages/chris-ware/nova-breadcrumbs
